# Generated by Django 5.2.8 on 2025-12-18 06:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email for login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(auto_now_add=True, verbose_name='date issued')),
                ('task_date', models.DateField(verbose_name='the task date')),
                ('task', models.CharField(max_length=70, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='verbose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=70, verbose_name='title')),
                ('start_working_at', models.DateTimeField(blank=True, null=True, verbose_name='start_time')),
                ('issued_date', models.DateTimeField(auto_now_add=True, verbose_name='issued_date')),
                ('task_date', models.DateTimeField(verbose_name=' ..complete  time when suppose to finish')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description ')),
                ('time_based', models.BooleanField(verbose_name='time based')),
                ('working', models.BooleanField(default=False, verbose_name='working')),
                ('completed', models.BooleanField(verbose_name='completed or not task')),
                ('daily_based', models.BooleanField(verbose_name='daily_based')),
                ('total_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name=' total time invested for task ')),
                ('daily_completed_count', models.IntegerField(blank=True, null=True, verbose_name='dialy_completed count')),
                ('completed_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='completed duration')),
                ('daily_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='time daily to set ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_times_activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todos_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('time_spend', models.DurationField(default=datetime.timedelta(0), verbose_name='time-spend ')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='its_history', to='core.todos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dailytodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working', models.BooleanField(default=False, verbose_name='working')),
                ('start_working_at', models.DateTimeField(blank=True, null=True, verbose_name='start_time')),
                ('task', models.CharField(max_length=70, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description ')),
                ('time_based', models.BooleanField(verbose_name='time based')),
                ('completed', models.BooleanField(verbose_name='completed or not ')),
                ('completed_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='completed duration')),
                ('daily_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='time invested for task ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_daily_activity', to=settings.AUTH_USER_MODEL)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_daily_total_investment', to='core.todos')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_todo', to='core.todos_history')),
            ],
        ),
    ]
