# Generated by Django 5.2.8 on 2025-12-03 07:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(auto_now_add=True, verbose_name='date issued')),
                ('task_date', models.DateField(verbose_name='the task date')),
                ('task', models.CharField(max_length=70, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='verbose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=70, verbose_name='title')),
                ('start_working_at', models.DateTimeField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='start_time')),
                ('issued_date', models.DateTimeField(auto_now_add=True, verbose_name='issued_date')),
                ('task_date', models.DateTimeField(verbose_name='complete time')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description ')),
                ('time_based', models.BooleanField(verbose_name='time based')),
                ('working', models.BooleanField(default=False, verbose_name='working')),
                ('completed', models.BooleanField(verbose_name='completed or not ')),
                ('daily_based', models.BooleanField(verbose_name='daily_based')),
                ('total_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='time invested for task ')),
                ('completed_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='completed duration')),
                ('daily_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='time daily base ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_times_activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todos_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('time_spend', models.DurationField(default=datetime.timedelta(0), verbose_name='time-spend ')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='its_history', to='core.todos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dailytodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working', models.BooleanField(default=False, verbose_name='working')),
                ('start_working_at', models.DateTimeField(blank=True, null=True, verbose_name='start_time')),
                ('task', models.CharField(max_length=70, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description ')),
                ('time_based', models.BooleanField(verbose_name='time based')),
                ('completed', models.BooleanField(verbose_name='completed or not ')),
                ('completed_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='completed duration')),
                ('daily_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='time invested for task ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_daily_activity', to=settings.AUTH_USER_MODEL)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_daily_total_investment', to='core.todos')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_todo', to='core.todos_history')),
            ],
        ),
    ]
