# Generated by Django 5.2.8 on 2025-12-03 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='completed',
            field=models.BooleanField(verbose_name='completed or not task'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='daily_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='time daily to set '),
        ),
        migrations.AlterField(
            model_name='todos',
            name='total_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name=' total time invested for task '),
        ),
    ]
