# Generated by Django 5.2.8 on 2025-12-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_todos_completed_alter_todos_daily_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='task_date',
            field=models.DateTimeField(verbose_name=' ..complete  time when suppose to finish'),
        ),
    ]
