# Generated by Django 5.2.8 on 2025-12-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_todos_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='task_date',
            field=models.DateTimeField(verbose_name=' complete  time when suppose to finish'),
        ),
    ]
