# Generated by Django 5.2.8 on 2025-12-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_todos_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='total_daily_completed',
            field=models.IntegerField(blank=True, null=True, verbose_name='dialy_completed'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='start_working_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start_time'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='task_date',
            field=models.DateTimeField(verbose_name=' ..complete  time when suppose to finish'),
        ),
    ]
